OWNER=nielsbohr
IMAGE=migrid
TAG=edge

build:
	docker build -t ${OWNER}/${IMAGE}:${TAG} .

init:
 	# directory used as the volume target for the
	# certificates generated by migrid
	# docker volume rm -f $(docker volume ls -q -f 'name=docker-migrid*')
	rm -rf ./certs
	rm -rf ./httpd
	rm -rf ./mig
	rm -rf ./state
	mkdir -p ./certs
	mkdir -p ./httpd
	mkdir -p ./mig
	mkdir -p ./state

push:
	docker push ${OWNER}/${IMAGE}:${TAG}
