OWNER=nielsbohr
IMAGE=migrid
TAG=edge

build:
	# directory used as the volume target for the 
	# certificates generated by migrid
	mkdir -p ./certs
	mkdir -p ./httpd
	mkdir -p ./mig-conf
	docker build -t ${OWNER}/${IMAGE}:${TAG} .
push:
	docker push ${OWNER}/${IMAGE}:${TAG}
